### ISSUE TITLE
Constant Logouts

### ISSUE THREAD

**Issue by GabrielHogan** [ZJX-ARTCC/jacksonville-issue-tracker#6]
**Describe the bug**
Got to figure out why the website just keeps randomly logging people out.

**Additional context**
None currently available.

**Comment by GabrielHogan** [comment]
Issue appears to have been fixed. Awaiting further testing

**Comment by brinbrody** [comment]
This is not fixed: I am logged out consistently.

All browsers (Edge Beta, Chrome, Edge, Firefox) experience the issue.

**Comment by GabrielHogan** [comment]
Further investigation finds that this issue is somehow connected with the way Cloudflare is affecting the production site. Again, further investigation needed.

**Comment by brinbrody** [comment]
Adjustment to VATUSA redirect (http v. https  and www vs. no) has resolved this issue. Closing.
